### ISSUE TITLE
Issues with multiple sensors.

### ISSUE THREAD

**Issue by remizorrr** [SingleTact/StandaloneArduino#2]
I bought 2 sensors with boards and connected them via I2C to arduino UNO/ELEGOO board.

The sensors works fine, when only one is connected, but when there is 2, the example code SingleTactMultiSensorDemo is not working.

I have changed the board I2C address via the .Net application. so one is 0x04, and other is 0x05.

in short `readDataFromSensor(short address)` only 5 bytes are received for the first request.
If this error is ignored, the app freezes on `Wire.endTransmission()`

**Comment by dayizhang** [comment]
Could yo change the address from 0x04 to 0x06 and try again?

**Comment by remizorrr** [comment]
It did help! Thank you.

BTW the scanner was weirdly showing 3 sensors - 0x04,0x05,0x06, when there was only 2 connected, 0x05, 0x06.

With the correct addresses - everything works now.

**Comment by dayizhang** [comment]
0x04 is a default address. If you change the address to another value, such as 0x05, the device actually has two addresses, 0x04 and 0x05.

**Comment by squilliam** [comment]
Could you provide any materials on your pinout for multiple sensors on one board? Or did you use multiple Arduino boards? (Asking for a friend ;) )

**Comment by tiantianfeng** [comment]
1. You will certainly wire all I2C wire together.

2.You will configure the i2c address for each sensor to be different from
the others. Likely use PC App to change I2C address for each board.

Thanks,

Tiantian

On Oct 12, 2017 10:19, "squilliam" <notifications@github.com> wrote:

Could you provide any materials on your pinout for multiple sensors on one
board? Or did you use multiple Arduino boards? (Asking for a friend ;) )

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SingleTact/StandaloneArduino/issues/2#issuecomment-336206177>,
or mute the thread
